"""PDF Report Renderer (Phase 4.0 Part 3 — Sections 29-34).

Generates production-safe PDF documents containing all authoritative sections,
risk metrics, evidence cards, recommendations, and technical details.
"""

from typing import Any, Optional, Dict
from app.schemas.digital_trust_report_models import ReportDocumentDTO
from app.schemas.trust_narrative_models import NarrativeDocumentDTO
from app.services.renderers.base_renderer import BaseReportRenderer


class PDFReportRenderer(BaseReportRenderer):
    """Production-grade PDF Report Renderer generating valid PDF 1.4 documents."""

    VERSION = "1.0.0"

    def validate_input(
        self,
        report_doc: ReportDocumentDTO,
        narrative_doc: Optional[NarrativeDocumentDTO] = None,
    ) -> bool:
        if not report_doc or not report_doc.report_id:
            return False
        return True

    def render(
        self,
        report_doc: ReportDocumentDTO,
        narrative_doc: Optional[NarrativeDocumentDTO] = None,
        options: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        self.validate_input(report_doc, narrative_doc)

        ov = report_doc.trust_overview
        risk_score = ov.risk_score
        risk_band = ov.risk_band
        confidence = ov.confidence
        sufficiency = ov.evidence_sufficiency

        # Build lines of text that must appear in the PDF
        lines = [
            "TRUTHSHIELD X — DIGITAL TRUST REPORT",
            "=====================================",
            f"Report ID: {report_doc.report_id}",
            f"Analysis ID: {report_doc.analysis_id}",
            f"Report Version: {report_doc.report_version}",
            f"Schema Version: {report_doc.schema_version}",
            f"Generated At: {report_doc.generated_at}",
            "",
            "EXECUTIVE SUMMARY",
            "-----------------",
        ]

        if narrative_doc and narrative_doc.executive_summary:
            lines.append(f"Headline: {narrative_doc.executive_summary.headline}")
            lines.append(f"Assessment: {narrative_doc.executive_summary.overall_assessment}")
            lines.append(f"Recommended Action: {narrative_doc.executive_summary.recommended_action}")
        else:
            lines.append(f"Overall Assessment: The analysis concluded with risk band {risk_band}.")

        lines.extend([
            "",
            "TRUST OVERVIEW & RISK ASSESSMENT",
            "---------------------------------",
            f"Risk Score: {risk_score:.1f} / 100",
            f"Risk Band: {risk_band}",
            f"Confidence: {confidence}",
            f"Evidence Sufficiency: {sufficiency}",
            f"Findings Count: {ov.findings_count}",
            f"Evidence Records: {ov.evidence_count}",
            f"Threat Matches: {ov.threat_matches}",
            f"Contradictions: {ov.contradictions}",
            "",
            "MAJOR FINDINGS",
            "--------------",
        ])

        if report_doc.major_findings:
            for f in report_doc.major_findings:
                lines.append(f"Finding [{f.finding_id}]: {f.title}")
                lines.append(f"  Category: {f.category} | Confidence: {f.confidence} | Strength: {f.evidence_strength}")
                lines.append(f"  Description: {f.description}")
                if f.provenance_reference:
                    lines.append(f"  Provenance Ref: {f.provenance_reference}")
        else:
            lines.append("No major security findings identified.")

        lines.extend([
            "",
            "RECOMMENDATIONS",
            "---------------",
        ])
        if report_doc.recommendations:
            for i, rec in enumerate(report_doc.recommendations, 1):
                lines.append(f"{i}. {rec}")
        else:
            lines.append("No specific actions required.")

        lines.extend([
            "",
            "LIMITATIONS",
            "-----------",
        ])
        if report_doc.limitations:
            for lim in report_doc.limitations:
                lines.append(f"- {lim}")
        else:
            lines.append("- Standard static analysis limitations apply.")

        lines.extend([
            "",
            "TECHNICAL APPENDIX & PROVENANCE",
            "--------------------------------",
            f"Generated By: {report_doc.generated_by}",
            f"Renderer: PDFReportRenderer v{self.VERSION}",
        ])

        if report_doc.provenance:
            for p in report_doc.provenance:
                lines.append(f"Statement {p.statement_id}: Module={p.source_module} Finding={p.finding_id} Evidence={p.evidence_id} Time={p.timestamp}")

        # Assemble into valid PDF 1.4 binary structure
        pdf_bytes = self._build_pdf_binary(lines)
        return pdf_bytes

    def _build_pdf_binary(self, text_lines: list) -> bytes:
        """Construct a minimal valid PDF-1.4 file containing the specified text."""
        # Sanitize text lines for PDF string literals
        escaped_text_cmds = []
        y_pos = 750
        escaped_text_cmds.append("BT /F1 10 Tf 50 750 Td 12 TL")
        for line in text_lines:
            safe_line = line.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")
            escaped_text_cmds.append(f"({safe_line}) '")
        escaped_text_cmds.append("ET")

        content_stream = "\n".join(escaped_text_cmds).encode("latin1", errors="replace")
        stream_len = len(content_stream)

        objects = []
        # Object 1: Catalog
        objects.append(b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n")
        # Object 2: Pages
        objects.append(b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n")
        # Object 3: Page
        objects.append(b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n")
        # Object 4: Contents Stream
        objects.append(f"4 0 obj\n<< /Length {stream_len} >>\nstream\n".encode("latin1") + content_stream + b"\nendstream\nendobj\n")
        # Object 5: Font
        objects.append(b"5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n")

        # Calculate xref offsets
        header = b"%PDF-1.4\n"
        offsets = [0]
        current_offset = len(header)
        for obj in objects:
            offsets.append(current_offset)
            current_offset += len(obj)

        xref = f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n".encode("latin1")
        for off in offsets[1:]:
            xref += f"{off:010d} 00000 n \n".encode("latin1")

        trailer = f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{current_offset}\n%%EOF\n".encode("latin1")

        return header + b"".join(objects) + xref + trailer

    def validate_output(self, rendered_bytes: bytes) -> bool:
        if not rendered_bytes or len(rendered_bytes) < 32:
            return False
        return rendered_bytes.startswith(b"%PDF-1.") and b"%%EOF" in rendered_bytes

    def get_content_type(self) -> str:
        return "application/pdf"

    def get_file_extension(self) -> str:
        return "pdf"

    def get_renderer_version(self) -> str:
        return self.VERSION
