"""
TruthShield X — Continuous Operations & Self-Healing REST API Endpoints
========================================================================
Exposes endpoints for:
- System & Subsystem Health Monitoring
- Security Invariant Verification & Incident Reporting
- Drift Detection & Schema Integrity
- Continuous Validation Cycle Triggering
- Safe Self-Healing Actions
- Emergency Lockdown & Maintenance Mode Control
"""

from fastapi import APIRouter, HTTPException, Depends
from typing import Dict, Any, Optional
from pydantic import BaseModel

from app.services.continuous_operations import (
    production_health_engine,
    security_invariant_engine,
    continuous_drift_engine,
    continuous_validation_orchestrator,
)

router = APIRouter(prefix="/continuous-operations", tags=["Continuous Operations & Quality Gate"])


class SelfHealingRequest(BaseModel):
    action_type: str
    target: str
    tenant_id: Optional[str] = "org_default"


class LockdownRequest(BaseModel):
    reason: str
    triggered_by: Optional[str] = "SecOps_Automated_Guardian"


class MaintenanceRequest(BaseModel):
    enabled: bool


@router.get("/health")
async def get_production_health() -> Dict[str, Any]:
    """Returns comprehensive 12-subsystem health status and 6D executive health scores."""
    return production_health_engine.run_full_system_health_audit()


@router.get("/invariants")
async def get_security_invariants(tenant_id: str = "org_default") -> Dict[str, Any]:
    """Runs automated verification of the 7 absolute security invariants."""
    return security_invariant_engine.verify_all_invariants(tenant_id=tenant_id)


@router.get("/invariants/incidents")
async def get_invariant_incidents(tenant_id: Optional[str] = None) -> Dict[str, Any]:
    """Retrieves security incidents generated by invariant violations."""
    incidents = security_invariant_engine.get_incidents(tenant_id=tenant_id)
    return {"incidents_count": len(incidents), "incidents": incidents}


@router.get("/drift/events")
async def get_drift_events(drift_type: Optional[str] = None) -> Dict[str, Any]:
    """Retrieves tracked drift events across configuration, release, database, feeds, and AI."""
    events = continuous_drift_engine.get_drift_events(drift_type=drift_type)
    return {"drift_events_count": len(events), "drift_events": events}


@router.post("/validate")
async def trigger_continuous_validation_cycle(tenant_id: str = "org_default") -> Dict[str, Any]:
    """Triggers an end-to-end continuous validation and security verification cycle."""
    return continuous_validation_orchestrator.run_continuous_validation_cycle(tenant_id=tenant_id)


@router.post("/self-healing/execute")
async def execute_safe_self_healing(request: SelfHealingRequest) -> Dict[str, Any]:
    """Executes a strictly SAFE automated remediation action with post-verification."""
    result = continuous_validation_orchestrator.execute_safe_self_healing(
        action_type=request.action_type,
        target=request.target,
        tenant_id=request.tenant_id or "org_default"
    )
    if not result.get("success", False):
        raise HTTPException(status_code=400, detail=result.get("error", "Remediation failed"))
    return result


@router.post("/emergency-lockdown/activate")
async def activate_emergency_lockdown(request: LockdownRequest) -> Dict[str, Any]:
    """Activates system-wide Emergency Lockdown mode."""
    return continuous_validation_orchestrator.trigger_emergency_lockdown(
        reason=request.reason,
        triggered_by=request.triggered_by or "SecOps_Automated_Guardian"
    )


@router.post("/emergency-lockdown/deactivate")
async def deactivate_emergency_lockdown(authorization_token: str = "VALID_SECOPS_TOKEN") -> Dict[str, Any]:
    """Deactivates Emergency Lockdown mode."""
    return continuous_validation_orchestrator.deactivate_emergency_lockdown(authorization_token=authorization_token)


@router.post("/maintenance-mode")
async def toggle_maintenance_mode(request: MaintenanceRequest) -> Dict[str, Any]:
    """Toggles Maintenance Mode while preserving security invariants and audit continuity."""
    return continuous_validation_orchestrator.set_maintenance_mode(enabled=request.enabled)
